/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-05-08 23:55:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class mods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>GameVerse Academy — Mods</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&family=Syne:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write(".user-info {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: var(--text);\r\n");
      out.write("    transition: color .2s;\r\n");
      out.write("}\r\n");
      out.write(".user-info:hover { color: var(--accent); }\r\n");
      out.write("\r\n");
      out.write(".logout-btn {\r\n");
      out.write("    background: rgba(74,144,217,.2);\r\n");
      out.write("    border: 1px solid var(--accent);\r\n");
      out.write("    color: var(--text);\r\n");
      out.write("    font-family: 'Syne', sans-serif;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    padding: 6px 14px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: all .2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-btn:hover {\r\n");
      out.write("    background: var(--accent);\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        :root {\r\n");
      out.write("            --bg-deep:    #0B0F1A;\r\n");
      out.write("            --bg-card:    #111827;\r\n");
      out.write("            --bg-card2:   #1a2235;\r\n");
      out.write("            --accent:     #4A90D9;\r\n");
      out.write("            --accent2:    5#00D4FF;\r\n");
      out.write("            --gold:       #F5C542;\r\n");
      out.write("            --text:       #E2E8F0;\r\n");
      out.write("            --muted:      #94A3B8;\r\n");
      out.write("            --border:     rgba(74,144,217,0.18);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            background: var(--bg-deep);\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Background mesh ── */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed; inset: 0; z-index: 0;\r\n");
      out.write("            background:\r\n");
      out.write("                radial-gradient(ellipse 70% 50% at 10% 20%, rgba(74,144,217,.12) 0%, transparent 65%),\r\n");
      out.write("                radial-gradient(ellipse 60% 60% at 90% 80%, rgba(0,212,255,.08) 0%, transparent 60%);\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Nav ── */\r\n");
      out.write("        nav {\r\n");
      out.write("            position: sticky; top: 0; z-index: 100;\r\n");
      out.write("            display: flex; align-items: center; gap: 24px;\r\n");
      out.write("            padding: 0 40px;\r\n");
      out.write("            height: 62px;\r\n");
      out.write("            background: rgba(11,15,26,.82);\r\n");
      out.write("            backdrop-filter: blur(18px);\r\n");
      out.write("            border-bottom: 1px solid var(--border);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-logo {\r\n");
      out.write("            font-family: 'Orbitron', sans-serif;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--accent2);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-logo span { color: var(--gold); }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex; gap: 6px;\r\n");
      out.write("            margin-left: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: .5px;\r\n");
      out.write("            padding: 6px 14px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all .2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a:hover, .nav-links a.active {\r\n");
      out.write("            color: var(--text);\r\n");
      out.write("            background: rgba(74,144,217,.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Page wrapper ── */\r\n");
      out.write("        .page {\r\n");
      out.write("            position: relative; z-index: 1;\r\n");
      out.write("            max-width: 1240px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 48px 28px 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Header row ── */\r\n");
      out.write("        .page-header {\r\n");
      out.write("            display: flex; align-items: flex-end; gap: 20px;\r\n");
      out.write("            margin-bottom: 36px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-header h1 {\r\n");
      out.write("            font-family: 'Orbitron', sans-serif;\r\n");
      out.write("            font-size: clamp(22px, 3vw, 32px);\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            background: linear-gradient(90deg, #4A90D9, #00D4FF);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-header .sub {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("            margin-left: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Filter tabs ── */\r\n");
      out.write("        .tabs {\r\n");
      out.write("            display: flex; gap: 8px; flex-wrap: wrap;\r\n");
      out.write("            margin-bottom: 32px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab {\r\n");
      out.write("            padding: 7px 18px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 13px; font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: 1px solid transparent;\r\n");
      out.write("            transition: all .2s;\r\n");
      out.write("            background: var(--bg-card2);\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab.active, .tab:hover {\r\n");
      out.write("            background: var(--accent);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-color: var(--accent);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Cards grid ── */\r\n");
      out.write("        .cards-container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));\r\n");
      out.write("            gap: 28px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Individual card ── */\r\n");
      out.write("        .card {\r\n");
      out.write("            background: var(--bg-card);\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border: 1px solid var(--border);\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0,0,0,.45);\r\n");
      out.write("            transition: transform .28s ease, box-shadow .28s ease;\r\n");
      out.write("            display: flex; flex-direction: column;\r\n");
      out.write("            animation: fadeUp .5s ease both;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:nth-child(1) { animation-delay: .05s; }\r\n");
      out.write("        .card:nth-child(2) { animation-delay: .12s; }\r\n");
      out.write("        .card:nth-child(3) { animation-delay: .19s; }\r\n");
      out.write("        .card:nth-child(4) { animation-delay: .26s; }\r\n");
      out.write("        .card:nth-child(5) { animation-delay: .33s; }\r\n");
      out.write("        .card:nth-child(6) { animation-delay: .40s; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeUp {\r\n");
      out.write("            from { opacity:0; transform:translateY(24px); }\r\n");
      out.write("            to   { opacity:1; transform:translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-6px);\r\n");
      out.write("            box-shadow: 0 16px 48px rgba(74,144,217,.22);\r\n");
      out.write("            border-color: rgba(74,144,217,.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Thumbnail ── */\r\n");
      out.write("        .card-thumb {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 190px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-thumb img {\r\n");
      out.write("            width: 100%; height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            transition: transform .4s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover .card-thumb img { transform: scale(1.06); }\r\n");
      out.write("\r\n");
      out.write("        .card-thumb .badge {\r\n");
      out.write("            position: absolute; top: 12px; left: 12px;\r\n");
      out.write("            background: rgba(74,144,217,.85);\r\n");
      out.write("            backdrop-filter: blur(6px);\r\n");
      out.write("            font-size: 11px; font-weight: 700;\r\n");
      out.write("            letter-spacing: .6px; text-transform: uppercase;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 4px 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Content ── */\r\n");
      out.write("        .card-content {\r\n");
      out.write("            padding: 18px 20px;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex; flex-direction: column; gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-content h3 {\r\n");
      out.write("            font-family: 'Orbitron', sans-serif;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            line-height: 1.35;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-meta {\r\n");
      out.write("            display: flex; align-items: center; gap: 8px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-meta .author {\r\n");
      out.write("            font-size: 12px; color: var(--muted);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-meta .dot { color: var(--border); }\r\n");
      out.write("\r\n");
      out.write("        .card-meta .platform {\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            color: var(--accent2);\r\n");
      out.write("            background: rgba(0,212,255,.08);\r\n");
      out.write("            padding: 2px 8px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border: 1px solid rgba(0,212,255,.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-desc {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: #9aafc7;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: -webkit-box;\r\n");
      out.write("            -webkit-line-clamp: 3;\r\n");
      out.write("            -webkit-box-orient: vertical;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ── Footer ── */\r\n");
      out.write("        .card-footer {\r\n");
      out.write("            display: flex; align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            padding: 12px 20px 18px;\r\n");
      out.write("            border-top: 1px solid rgba(255,255,255,.05);\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dl-count {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("            display: flex; align-items: center; gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dl-count svg { opacity: .7; }\r\n");
      out.write("\r\n");
      out.write("        .btn-voir {\r\n");
      out.write("            background: linear-gradient(135deg, #4A90D9, #00a8cc);\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 18px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-family: 'Syne', sans-serif;\r\n");
      out.write("            font-size: 13px; font-weight: 700;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            letter-spacing: .4px;\r\n");
      out.write("            transition: opacity .2s, transform .15s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-voir:hover { opacity: .85; transform: scale(1.04); }\r\n");
      out.write("\r\n");
      out.write("        /* ── Empty state ── */\r\n");
      out.write("        .empty {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 80px 20px;\r\n");
      out.write("            color: var(--muted);\r\n");
      out.write("        }\r\n");
      out.write("        .empty h2 { font-family:'Orbitron',sans-serif; font-size:20px; margin-bottom:10px; }\r\n");
      out.write("\r\n");
      out.write("        /* ── Responsive ── */\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            nav { padding: 0 16px; }\r\n");
      out.write("            .page { padding: 28px 14px 60px; }\r\n");
      out.write("            .cards-container { grid-template-columns: 1fr; }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        /* ── Search bar ── */\r\n");
      out.write(".search-form {\r\n");
      out.write("    margin-bottom: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background: var(--bg-card);\r\n");
      out.write("    border: 1px solid var(--border);\r\n");
      out.write("    border-radius: 14px;\r\n");
      out.write("    padding: 6px 6px 6px 16px;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    transition: border-color .2s, box-shadow .2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar:focus-within {\r\n");
      out.write("    border-color: var(--accent);\r\n");
      out.write("    box-shadow: 0 0 0 3px rgba(74,144,217,.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-icon {\r\n");
      out.write("    color: var(--muted);\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    flex-shrink: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-input {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    color: var(--text);\r\n");
      out.write("    font-family: 'Syne', sans-serif;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 6px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-input::placeholder {\r\n");
      out.write("    color: var(--muted);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-btn {\r\n");
      out.write("    background: linear-gradient(135deg, #4A90D9, #00a8cc);\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 8px 20px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-family: 'Syne', sans-serif;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: .2s;\r\n");
      out.write("    flex-shrink: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-btn:hover {\r\n");
      out.write("    opacity: .85;\r\n");
      out.write("    transform: scale(1.03);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-clear {\r\n");
      out.write("    color: var(--muted);\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 6px 10px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    transition: .2s;\r\n");
      out.write("    flex-shrink: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-clear:hover {\r\n");
      out.write("    color: #ff6b6b;\r\n");
      out.write("    background: rgba(255,107,107,.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ── Search result message ── */\r\n");
      out.write(".search-result-msg {\r\n");
      out.write("    background: rgba(74,144,217,.08);\r\n");
      out.write("    border: 1px solid rgba(74,144,217,.2);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding: 10px 16px;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    color: var(--muted);\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-result-msg strong {\r\n");
      out.write("    color: var(--accent2);\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ════ Navigation ════ -->\r\n");
      out.write("<nav>\r\n");
      out.write("    <a class=\"nav-logo\" href=\"#\">Game<span>Verse</span> Academy</a>\r\n");
      out.write("    <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"home.html\">Accueil</a>\r\n");
      out.write("        <a href=\"mods\">Mods</a>\r\n");
      out.write("        <a href=\"ModSubmitController\">Soumettre</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ProfileController\" class=\"user-info\">\r\n");
      out.write("    <i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("    <span>\r\n");
      out.write("        ");
      out.print( session.getAttribute("user") != null
            ? session.getAttribute("user") : "Visiteur" );
      out.write("\r\n");
      out.write("    </span>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("        <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("            <i class=\"bi bi-box-arrow-right\"></i> Déconnexion\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- ════ Page ════ -->\r\n");
      out.write("<div class=\"page\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"page-header\">\r\n");
      out.write("        <h1>Bibliothèque de Mods</h1>\r\n");
      out.write("        <span class=\"sub\">Tous les mods disponibles</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <!-- ══ Barre de recherche ══ -->\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/mods\" method=\"get\" class=\"search-form\">\r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("            <i class=\"bi bi-search search-icon\"></i>\r\n");
      out.write("            <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                name=\"search\"\r\n");
      out.write("                class=\"search-input\"\r\n");
      out.write("                placeholder=\"Rechercher par titre, catégorie, auteur...\"\r\n");
      out.write("                value=\"");
      out.print( request.getAttribute("search") != null ? request.getAttribute("search") : "" );
      out.write("\"\r\n");
      out.write("                autocomplete=\"off\"\r\n");
      out.write("            >\r\n");
      out.write("            <button type=\"submit\" class=\"search-btn\">Rechercher</button>\r\n");
      out.write("            ");
 if (request.getAttribute("search") != null &&
                   !request.getAttribute("search").toString().isEmpty()) { 
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mods\" class=\"search-clear\">\r\n");
      out.write("                <i class=\"bi bi-x-lg\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Message résultat de recherche -->\r\n");
      out.write("    ");
 if (request.getAttribute("search") != null &&
           !request.getAttribute("search").toString().isEmpty()) { 
      out.write("\r\n");
      out.write("    <div class=\"search-result-msg\">\r\n");
      out.write("        Résultats pour : <strong>\"");
      out.print( request.getAttribute("search") );
      out.write("\"</strong>\r\n");
      out.write("        — ");
      out.print( request.getAttribute("count") );
      out.write(" mod(s) trouvé(s)\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- ══ Cards Grid ══ -->\r\n");
      out.write("    <div class=\"cards-container\">\r\n");
      out.write("\r\n");
      out.write("    ");

        /* ── Image mapping helper ── */
        java.util.Map<String,String> imgMap = new java.util.LinkedHashMap<>();
        imgMap.put("elder scrolls",  "assets/images/elder-scrolls-skyrim.jpg");
        imgMap.put("skyrim",         "assets/images/elder-scrolls-skyrim.jpg");
        imgMap.put("fallout",        "assets/images/Fallout_4.jpg");
        imgMap.put("grand theft",    "assets/images/grandThief.jpg");
        imgMap.put("gta",            "assets/images/grandThief.jpg");
        imgMap.put("mario",          "assets/images/superMario.jpg");

        String defaultImg = "assets/images/elder-scrolls-skyrim.jpg";

        List<Mod> mods = (List<Mod>) request.getAttribute("mods");
        if (mods != null && !mods.isEmpty()) {
            for (Mod mod : mods) {

                /* Choose image by matching title keywords */
                String img = defaultImg;
                String titleLower = mod.getTitle() == null ? "" : mod.getTitle().toLowerCase();
                for (java.util.Map.Entry<String,String> e : imgMap.entrySet()) {
                    if (titleLower.contains(e.getKey())) { img = e.getValue(); break; }
                }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-thumb\">\r\n");
      out.write("                <img src=\"");
      out.print( img );
      out.write("\" alt=\"");
      out.print( mod.getTitle() );
      out.write("\">\r\n");
      out.write("                <span class=\"badge\">");
      out.print( mod.getCategory() != null ? mod.getCategory() : "Mod" );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <h3>");
      out.print( mod.getTitle() );
      out.write("</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-meta\">\r\n");
      out.write("                    <span class=\"author\">By ");
      out.print( mod.getAuthor() );
      out.write("</span>\r\n");
      out.write("                    <span class=\"dot\">•</span>\r\n");
      out.write("                    <span class=\"platform\">PC</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"card-desc\">");
      out.print( mod.getDescription() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-footer\">\r\n");
      out.write("                <span class=\"dl-count\">\r\n");
      out.write("                    <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                         stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\">\r\n");
      out.write("                        <path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/>\r\n");
      out.write("                        <polyline points=\"7 10 12 15 17 10\"/>\r\n");
      out.write("                        <line x1=\"12\" y1=\"15\" x2=\"12\" y2=\"3\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    ");
      out.print( mod.getDownloads() );
      out.write(" téléchargements\r\n");
      out.write("                </span>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ReviewController?modId=");
      out.print( mod.getId() );
      out.write("\">\r\n");
      out.write("                <button class=\"btn-voir\">Voir reviews</button>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    ");

            } /* end for */
        } else { /* empty state */
    
      out.write("\r\n");
      out.write("        <div class=\"empty\" style=\"grid-column:1/-1\">\r\n");
      out.write("            <h2>Aucun mod trouvé</h2>\r\n");
      out.write("            <p>Il n'y a pas encore de mods disponibles.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
